### ISSUE TITLE
SKT：可以用Windows系统复现吗?

### ISSUE THREAD

**Issue by Dajcaac** [bigdata-ustc/XKT#14]
论文中是在Linux服务器下进行训练的，我想问一下这个项目可以用Windows系统跑吗？谢谢

**Comment by Dajcaac** [comment]
windows系统mxnet1.7与其他包将numpy的版本限制在1.6.5-1.7.0之间，但此版本区间的模块 'numpy.random' 没有属性 'default_rng'，这个问题怎么解决呢

**Comment by tswsxk** [comment]
可以在windows下运行

**Comment by tswsxk** [comment]
你可以升级mxnet
